### ISSUE TITLE
zooming because of different satellites

### ISSUE THREAD

**Issue by buhtz** [apollo-ng/xfce-planet#8]
The pictures is zooming sometimes. I think this depends on the satellites which are displayed at that time.

But how can I modify that behaviour?
1. How can I modify which sat are displayed?
2. How can I setup sattelites without switching. Everytime the same satellites I mean?
3. How could I switch off the satellites?

**Comment by chron0** [comment]
Indeed, the geos are too far away to be visible in xplanets default viewing distance, so when the geo TLEs are rendered, the scripts zooms out to adapt.

In order to change/lock a TLE set, you'll have to hack around in xfce-planet.sh tp undo the auto feature:

https://github.com/apollo-ng/xfce-planet/blob/master/xfce-planet.sh#L116

and, if you want to have other birds also, download-tle.sh.

**Comment by chron0** [comment]
To disable sat rendering this might work

https://github.com/apollo-ng/xfce-planet/blob/master/xfce-planet.sh#L122

Comment out the following two lines, which should stop the config injection:

```
    #echo "satellite_file=${BASEDIR}/satellites/iss" > ${BASEDIR}/default
    #echo "satellite_file=${BASEDIR}/satellites/${SATFILE}" >> ${BASEDIR}/default
```

**Comment by buhtz** [comment]
In that line

`echo "${DEFCFG}" >> ${BASEDIR}/default`

the `>>` should become a `>`.

**Comment by chron0** [comment]
Ah, yes, good catch, otherwise it would start to stack up :)

**Comment by chron0** [comment]
@Codeberg-AsGithubAlternative-buhtz 

lulz, better late then never, ey? :)

**Comment by chron0** [comment]
btw, that was a red herring - echo "${DEFCFG}" >> ${BASEDIR}/default was correct...
